import data from "./data/melbourne-places.json";
import type { Place } from "./geo";

/**
 * Bundled gazetteer of Melbourne suburbs and landmarks generated by
 * `scripts/build_geodata.py` (coordinates from Photon / OpenStreetMap, ODbL).
 * Used for offline place search, the reverse-geocode fallback and to place the
 * synthetic seed meetings.
 */
export const PLACES: readonly Place[] = data.places as Place[];
export const PLACES_ATTRIBUTION: string = data.attribution;
