"use client";

import "maplibre-gl/dist/maplibre-gl.css";
import {
  forwardRef,
  useEffect,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
  type ReactNode,
} from "react";
import Map, {
  AttributionControl,
  NavigationControl,
  type MapLayerMouseEvent,
  type MapRef,
  type ViewState,
} from "react-map-gl/maplibre";
import { setWorkerUrl, type StyleSpecification } from "maplibre-gl";
import { useTheme } from "next-themes";
import { WifiOff } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * MapLibre GL + OpenFreeMap vector tiles (free, no key). If the tile style
 * can't be loaded (offline, blocked, outage) we switch to a bundled GeoJSON
 * basemap of Australia / Greater Melbourne generated by scripts/build_geodata.py.
 */

const OPENFREEMAP = {
  light: "https://tiles.openfreemap.org/styles/positron",
  dark: "https://tiles.openfreemap.org/styles/dark",
};
const STYLE_TIMEOUT_MS = 8000;
/**
 * MapLibre opens a compact attribution expanded and only collapses it on the
 * first drag, so on small maps it covers a fifth of the view. The OSMF
 * attribution guidelines allow a collapsible attribution once it has been
 * shown for a few seconds; the "i" button re-opens it.
 */
const ATTRIBUTION_COLLAPSE_MS = 5000;

// MapLibre v6 resolves its worker relative to its own (bundled) chunk URL; point
// it at the copy served from public/vendor (see scripts/copy-assets.mjs).
if (typeof window !== "undefined") setWorkerUrl("/vendor/maplibre/maplibre-gl-worker.mjs");

function fallbackStyle(dark: boolean): StyleSpecification {
  return {
    version: 8,
    sources: {
      base: {
        type: "geojson",
        data: "/data/basemap.geojson",
        attribution: "Natural Earth (public domain)",
      },
    },
    layers: [
      {
        id: "water",
        type: "background",
        paint: { "background-color": dark ? "#1b1d2b" : "#dfe6f2" },
      },
      // Coarse state outlines for the overview; above zoom 8 only the detailed
      // Greater Melbourne polygon is drawn so the bay coastline stays accurate.
      {
        id: "states",
        type: "fill",
        source: "base",
        maxzoom: 8,
        filter: ["==", ["get", "kind"], "state"],
        paint: { "fill-color": dark ? "#262838" : "#f6f6f4" },
      },
      {
        id: "states-outline",
        type: "line",
        source: "base",
        maxzoom: 8,
        filter: ["==", ["get", "kind"], "state"],
        paint: { "line-color": dark ? "#3c3f55" : "#c9cdd8", "line-width": 0.8 },
      },
      {
        id: "melbourne",
        type: "fill",
        source: "base",
        filter: ["==", ["get", "kind"], "detail"],
        paint: { "fill-color": dark ? "#262838" : "#f6f6f4" },
      },
      {
        id: "melbourne-coast",
        type: "line",
        source: "base",
        minzoom: 8,
        filter: ["==", ["get", "kind"], "detail"],
        paint: { "line-color": dark ? "#3c3f55" : "#c9cdd8", "line-width": 1 },
      },
    ],
  };
}

const subscribe = () => () => {};

export interface BaseMapProps {
  initialViewState: Partial<ViewState> & {
    bounds?: [[number, number], [number, number]];
    fitBoundsOptions?: { padding?: number; maxZoom?: number };
  };
  children?: ReactNode;
  className?: string;
  interactive?: boolean;
  onClick?: (e: MapLayerMouseEvent) => void;
  onLoad?: () => void;
  cursor?: string;
  showNavigation?: boolean;
  ariaLabel: string;
}

export const BaseMap = forwardRef<MapRef, BaseMapProps>(function BaseMap(
  {
    initialViewState,
    children,
    className,
    interactive = true,
    onClick,
    onLoad,
    cursor,
    showNavigation = true,
    ariaLabel,
  },
  ref,
) {
  const { resolvedTheme } = useTheme();
  const mounted = useSyncExternalStore(
    subscribe,
    () => true,
    () => false,
  );
  const dark = mounted && resolvedTheme === "dark";
  const [offline, setOffline] = useState(false);
  const loaded = useRef(false);
  const wrapper = useRef<HTMLDivElement>(null);
  const collapseTimer = useRef<number | undefined>(undefined);

  useEffect(() => () => window.clearTimeout(collapseTimer.current), []);

  const mapStyle = useMemo(
    () => (offline ? fallbackStyle(dark) : dark ? OPENFREEMAP.dark : OPENFREEMAP.light),
    [offline, dark],
  );

  useEffect(() => {
    if (offline) return;
    const t = window.setTimeout(() => {
      if (!loaded.current) setOffline(true);
    }, STYLE_TIMEOUT_MS);
    return () => window.clearTimeout(t);
  }, [offline, mapStyle]);

  return (
    <div
      ref={wrapper}
      className={cn("relative isolate overflow-hidden bg-muted", className)}
      role="region"
      aria-label={ariaLabel}
    >
      <Map
        ref={ref}
        initialViewState={initialViewState}
        mapStyle={mapStyle}
        interactive={interactive}
        cursor={cursor}
        onClick={onClick}
        attributionControl={false}
        dragRotate={false}
        touchPitch={false}
        style={{ position: "absolute", inset: 0 }}
        onLoad={() => {
          loaded.current = true;
          window.clearTimeout(collapseTimer.current);
          collapseTimer.current = window.setTimeout(() => {
            wrapper.current
              ?.querySelectorAll(".maplibregl-ctrl-attrib.maplibregl-compact-show")
              .forEach((el) => el.classList.remove("maplibregl-compact-show"));
          }, ATTRIBUTION_COLLAPSE_MS);
          onLoad?.();
        }}
        onStyleData={() => {
          loaded.current = true;
        }}
        onError={(e) => {
          // A failed style/source before first load means the tile service is unreachable.
          if (!loaded.current && !offline) {
            console.warn("[map] tiles unavailable, using bundled basemap", e.error?.message);
            setOffline(true);
          }
        }}
      >
        <AttributionControl compact position="bottom-right" />
        {interactive && showNavigation && (
          <NavigationControl position="top-right" showCompass={false} />
        )}
        {children}
      </Map>
      {offline && (
        <div className="absolute top-3 left-3 z-10 inline-flex items-center gap-1.5 rounded-full border bg-card/90 px-2.5 py-1 text-xs text-muted-foreground shadow-(--shadow-soft) backdrop-blur">
          <WifiOff className="size-3" aria-hidden="true" /> Offline basemap
        </div>
      )}
    </div>
  );
});
